### ISSUE TITLE
特定情况会卡死无法补充船员

### ISSUE THREAD

**Issue by lesser0** [by22dgb/evolvescript#1]
船员由默认工作的人口补充，而函数autoJobs()中，最后设置默认工作的条件是
if (settings.jobSetDefault && minDefault === 0)
minDefault为0即为当前不需要补充船员，本意应当是考虑需要补充船员时给默认工作保留了用于补充的人口，因此暂时不切换默认工作。但这没有考虑到默认工作没有人口可分配的情形，此时默认工作无人口，同时又不切换默认工作，导致船员无法补充。如果恰好出现在推进进度需要补充船员，并且人口基本满很难自然增长的时候，会卡上更长时间。

应当修改为，在前面计算需要分配的人口时：
let minEmployees = job.isDefault() ? minDefault : 0;
let jobsToAssign = Math.min(availableEmployees, Math.max(minEmployees, currentEmployees, job.breakpointEmployees(i)));
若当前是默认工作，job.isDefault()为真，且此时availableEmployees为0，从而无法分配人口到默认工作上，这时用一个变量记录下来。最后将设置默认工作的条件改为上述条件满足或无需补充船员则都设置默认工作：
if (settings.jobSetDefault && (minDefault === 0 || 满足上述条件))

**Comment by by22dgb** [comment]
具体条件麻烦描述一下，方便我来改动，毕竟源代码是来自Volch大佬的

**Comment by lesser0** [comment]
1. 

```
        let crewMissing = game.global.civic.crew.max - game.global.civic.crew.workers;
        let minDefault = crewMissing > 0 ? crewMissing + 1 : 0;
```
后加一行
`        let isSetDefault = (crewMissing === 0);`

2. 

`                availableEmployees -= jobsToAssign;`
后加
```
                if(job.isDefault() && availableEmployees === 0) {
                    isSetDefault = true;
                }
```

3. 

`        if (settings.jobSetDefault && minDefault === 0) {`
改为
`        if (settings.jobSetDefault && isSetDefault) {`

估计就可以了。
也就是当默认工作无人可分配时总是允许设置默认工作，而非只有无需补充船员时才允许设置默认工作。
